/**
 * Constantes para Saldo ATR
 */

import type { SaldoATRColumna } from '../../../types';

// Letras de columna A..AT (46 columnas)
export const COLUMN_LETTERS: readonly SaldoATRColumna[] = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'AA',
  'AB',
  'AC',
  'AD',
  'AE',
  'AF',
  'AG',
  'AH',
  'AI',
  'AJ',
  'AK',
  'AL',
  'AM',
  'AN',
  'AO',
  'AP',
  'AQ',
  'AR',
  'AS',
  'AT',
] as const;

// Columnas que deben quedar VACÍAS en la plantilla base
export const COLUMNS_TO_EMPTY = new Set<SaldoATRColumna>([
  'A',
  'B',
  'C',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'P',
]);

// Encabezados por defecto (fallback si no se ha importado archivo todavía)
export const DEFAULT_HEADERS: Partial<Record<string, string>> = {
  A: 'Número Fiscal de Factura',
  B: 'Potencia',
  C: 'Código de contrato externo - interfaz',
  D: 'Secuencial de factura',
  E: 'Tipo de factura',
  F: 'Estado de la factura',
  G: 'Fecha desde',
  H: 'Fecha hasta',
  I: 'Importe Factura',
  J: 'Fuente de la factura',
  K: 'Estado medida',
  L: 'Tipo de factura',
  M: 'Tipo de Fuente Anterior',
  N: 'Descripción Tipo de fuente Anterior',
  O: 'Tipo de punto de medida',
  P: 'Consumo P1/punta',
  Q: 'Consumo P2/llano',
  R: 'Consumo P3/valle',
  S: 'Consumo P4/supervalle',
  T: 'Consumo P5',
  U: 'Consumo P6',
  V: 'Consumo Reactiva1',
  W: 'Consumo Reactiva2',
  X: 'Consumo Reactiva3',
  Y: 'Consumo Reactiva4',
  Z: 'Consumo Reactiva5',
  AA: 'Consumo Reactiva6',
  AB: 'Consumo cargo-abono P1/punta',
  AC: 'Consumo cargo-abono P2/llano',
  AD: 'Consumo cargo-abono P3/valle',
  AE: 'Consumo cargo/abono P4',
  AF: 'Consumo cargo/abono P5',
  AG: 'Consumo cargo/abono P6',
  AH: 'Consumo pérdidas P1/punta',
  AI: 'Consumo pérdidas P2/llano',
  AJ: 'Consumo pérdidas P3/valle',
  AK: 'Consumo pérdidas P4',
  AL: 'Consumo pérdidas P5',
  AM: 'Consumo pérdidas P6',
  AN: 'Maxímetro P1/Punta',
  AO: 'Maxímetro P2/Llano',
  AP: 'Maxímetro P3/Valle',
  AQ: 'Maxímetro P4',
  AR: 'Maxímetro P5',
  AS: 'Maxímetro P6',
  AT: 'Origen',
};
